# Generated by Django 4.1.3 on 2022-12-05 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_player_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 11, 2, 10, 846907)),
        ),
    ]
