# Generated by Django 4.1.3 on 2022-12-07 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_player_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 11, 55, 49, 223649)),
        ),
    ]
