# Generated by Django 4.1.3 on 2022-12-07 16:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0005_alter_player_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 18, 58, 34, 772998)),
        ),
        migrations.CreateModel(
            name='Swing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 7, 18, 58, 34, 774997))),
                ('swing_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('shaft', models.CharField(choices=[('STIFF', 'Stiff'), ('REGULAR', 'Regular'), ('FLEX', 'Flex')], max_length=7)),
                ('weight_in_grams', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('club_type', models.CharField(choices=[('WOOD', 'Wood'), ('IRON', 'Iron')], max_length=4)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='swing',
            constraint=models.UniqueConstraint(fields=('username', 'time'), name='unique_migration_username_time'),
        ),
    ]
