# Generated by Django 4.1.3 on 2022-12-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_alter_player_registration_date_alter_swing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sensor_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 11, 52, 792150)),
        ),
        migrations.AlterField(
            model_name='swing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 11, 52, 793149)),
        ),
    ]
