# Generated by Django 4.1.3 on 2022-12-15 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_remove_player_sensor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 14, 35, 26023)),
        ),
        migrations.AlterField(
            model_name='swing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 14, 35, 27023)),
        ),
    ]
