# Generated by Django 4.1.3 on 2022-12-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_alter_player_registration_date_alter_swing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sensor_id',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 15, 33, 562864)),
        ),
        migrations.AlterField(
            model_name='swing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 19, 15, 33, 562864)),
        ),
    ]
