# Generated by Django 4.1.3 on 2022-12-31 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_alter_player_registration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swing',
            name='club_type',
        ),
        migrations.RemoveField(
            model_name='swing',
            name='shaft',
        ),
        migrations.RemoveField(
            model_name='swing',
            name='weight_in_grams',
        ),
        migrations.AddField(
            model_name='swing',
            name='x_velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='swing',
            name='y_velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='swing',
            name='z_velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 3, 8, 19, 488054)),
        ),
        migrations.AlterField(
            model_name='swing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 3, 8, 19, 488054)),
        ),
    ]
